; Commander X16 PETSCII/ISO Keyboard Table
;
; This definition file is NOT auto generated. `ja-jp.bin.lzsa` is generated by patching the ABC/X16.
; see `ja-jp_gen.py` to audit the patching process
;
; Name:   Japanese
; Locale: ja-JP
; 

.segment "KBDMETA"

	.byte "JA-JP", 0, 0, 0, 0, 0, 0, 0, 0, 0
	.word kbtab_jajp

.segment "KBDTABLES"

kbtab_jajp:
	.incbin "asm/ja-jp.bin.lzsa"

; PETSCII
; ~~~~~~~
; In petscii mode, the entire layout works exactly the same as the default ABC/X16 layout
; (although note that the CapsLock is disabled across the entire layout)

; ISO
; ~~~
; In ISO mode, this layout acts like a rudimentary IME, that allows the user to type katakana using romaji.
; dakuten and handakuten can be typed using ' and ; keys respectively and HAVE TO be typed manually (IME only produces diacriticless kana)

; small kana are produced by holding shift while typing. ン and small ッ can be produced by either Shift+n and Shift+t,
; or by pressing space after pressing n or t respectively.

; All of the JIS X 0201 interpunction can be typed without holding shift or alt key.
; By holding alt key, user can produce every character from the CX16 JIS Extensions (codepoints $E0-$FF) as well as the missing ASCII punctation.
